#!/bin/zsh

KERNEL=linux-lts
FULLFORMAT=false

if [ `whoami` != 'root' ]
then
    echo "Run as root"
    exit
fi

if [ -e /sys/firmware/efi/efivars ]
then
    echo "Efi! Cann't procced"
    exit
fi

timedatectl set-ntp true

lsblk
echo
read "?Select Disk: " DISK
DISK=/dev/`basename $DISK`

if $FULLFORMAT
then
    wipefs -fa $DISK
cat <<EOF | fdisk $DISK -W always
o
n
p


+200M
n
p


+16G
n
p


+4G
n
p



p
w
EOF
    partprobe
    yes | mkfs.ext4 ${DISK}4
fi

yes | mkfs.ext4 ${DISK}1
yes | mkfs.ext4 ${DISK}2
mkswap ${DISK}3

mkdir -p /mnt
mount ${DISK}2 /mnt

mkdir -p /mnt/{boot,home}
mount ${DISK}1 /mnt/boot
mount ${DISK}4 /mnt/home
swapon ${DISK}3

pacstrap /mnt base base-devel $KERNEL linux-firmware nano zsh
genfstab -U /mnt >/mnt/etc/fstab
echo $DISK >/mnt/disk.txt

arch-chroot /mnt

umount -R /mnt
swapoff ${DISK}3
