#!/bin/zsh

KERNEL=linux-lts
FULLFORMAT=false
USER='alby'
HOSTNAME='arch'
TIMEZONE='Asia/Kolkata'

if [ `whoami` != 'root' ]
then
    echo "Run as root"
    exit
fi

if [ -e /sys/firmware/efi/efivars ]
then
    echo "Efi! Cann't procced"
    exit
fi

timedatectl set-ntp true

lsblk
echo
read "?Select Disk: " DISK
DISK=/dev/`basename $DISK`

if $FULLFORMAT
then
    wipefs -fa $DISK
cat <<EOF | fdisk $DISK -W always
o
n
p


+200M
n
p


+16G
n
p


+4G
n
p



p
w
EOF
    partprobe
    yes | mkfs.ext4 ${DISK}4
fi

yes | mkfs.ext4 ${DISK}1
yes | mkfs.ext4 ${DISK}2
mkswap ${DISK}3

mkdir -p /mnt
mount ${DISK}2 /mnt

mkdir -p /mnt/{boot,home}
mount ${DISK}1 /mnt/boot
mount ${DISK}4 /mnt/home
swapon ${DISK}3

pacstrap /mnt base base-devel $KERNEL linux-firmware nano zsh
genfstab -U /mnt >/mnt/etc/fstab

cat <<EOF | arch-chroot /mnt
read "?Enter a password for the user: " PASS1
read "?Re-enter password :" PASS2
until [ "$PASS1" = "$PASS2" ]
do
	unset PASS1 PASS2
	read "?Enter a password for the user: " PASS1
	read "?Re-enter password :" PASS2
done

ln -sf /usr/share/zoneinfo/$TIMEZONE /etc/localtime
hwclock --systohc

echo "en_US.UTF-8 UTF-8" >/etc/locale.gen
echo "en_US ISO-8859-1" >>/etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" >/etc/locale.conf

echo $HOSTNAME >/etc/hostname
echo "127.0.0.1 localhost" >/etc/hosts

pacman --noconfirm -S grub intel-ucode
echo "add --removable to install on pendrive"
grub-install $DISK --recheck
sed -i "/GRUB_TIMEOUT_STYLE/c\GRUB_TIMEOUT_STYLE=hidden" /etc/default/grub
grub-mkconfig -o /boot/grub/grub.cfg

pacman --noconfirm -S networkmanager
systemctl enable NetworkManager

if [ -d /home/$USER ]
then
    cd /home/$USER
    OLD=$(date +'%b%d')
    mkdir $OLD

    DIR=(. .. aud code dl doc dt phone pic vid)
    DIR+=(.vim .gnupg .password-store .stardict)

    ALL=($(ls -a))
    MOV=($(printf "%s\n" $DIR $ALL | sort | uniq -u))

    mv $MOV $OLD
    cd
fi

useradd -m -g wheel -s /bin/zsh $USER
echo "$USER:$PASS1" | chpasswd
echo "root:$PASS1" | chpasswd
echo "%wheel ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

exit
EOF

umount -R /mnt
swapoff ${DISK}3
