#!/bin/zsh

KERNEL=linux-lts
USER='alby'
HOSTNAME='arch'
TIMEZONE='Asia/Kolkata'
PASS='1998'
#FULLFORMAT=true      #uncomment to do full format
#TARGET='--removable' #uncomment to install on pendrive

set -e
test $(whoami) = 'root'
test -e /sys/firmware/efi/efivars

timedatectl set-ntp true

lsblk
echo
read "?Select Disk: " DISK
DISK=/dev/`basename $DISK`

if $FULLFORMAT
then
    wipefs -fa $DISK
cat <<EOF | fdisk $DISK -W always
o
n
p


+200M
n
p


+16G
n
p


+4G
n
p



p
w
EOF
    yes | mkfs.ext4 ${DISK}4
fi

yes | mkfs.ext4 ${DISK}1
yes | mkfs.ext4 ${DISK}2
mkswap ${DISK}3

mkdir -p /mnt
mount ${DISK}2 /mnt

mkdir -p /mnt/{boot,home}
mount ${DISK}1 /mnt/boot
mount ${DISK}4 /mnt/home
swapon ${DISK}3

pacstrap /mnt base base-devel \
    $KERNEL linux-firmware \
    neovim zsh git \
    grub intel-ucode \
    networkmanager

genfstab -U /mnt >/mnt/etc/fstab
echo $DISK >/mnt/disk.txt

cat <<EOF | arch-chroot /mnt
set -e

ln -sf /usr/share/zoneinfo/$TIMEZONE /etc/localtime
hwclock --systohc

echo "en_US.UTF-8 UTF-8" >/etc/locale.gen
echo "en_US ISO-8859-1" >>/etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" >/etc/locale.conf

echo $HOSTNAME >/etc/hostname
echo "127.0.0.1 localhost" >/etc/hosts

grub-install $DISK --recheck $TARGET
sed -i "/GRUB_TIMEOUT_STYLE/c\GRUB_TIMEOUT_STYLE=hidden" /etc/default/grub
grub-mkconfig -o /boot/grub/grub.cfg

systemctl enable NetworkManager

if [ -d /home/$USER ]
then
    cd /home/$USER

    MY=(. .. aud code dl doc dt phone pic vid)
    MY+=(.vim .gnupg .password-store .stardict)

    LS=($(ls -a))
    CO=($(printf "%s\n" $MY $LS | sort | uniq -d))
    DF=($(printf "%s\n" $CO $LS | sort | uniq -u))

    TO=$(date +'%b%d')
    mkdir $TO
    mv $DF $TO
fi

useradd -m -g wheel -s /bin/zsh $USER
echo "$USER:$PASS" | chpasswd
echo "root:$PASS" | chpasswd
echo "%wheel ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
EOF

umount -R /mnt
swapoff ${DISK}3
