#!/bin/zsh

DIR=$HOME/code/aur

set -e

if [[ $EUID -eq 0 ]]; then
    echo "Don't run as root!"
    exit 1
fi

if ! [[ -d $DIR ]]; then mkdir -p $DIR; fi
cd $DIR

APP=()
ARG=()
while [[ $# -ne 0 ]]
do
    case "$1" in
--update|-u)

    APP=($(pacman -Qemq))
    ARG='--noconfirm'
    break ;;
--*)

    ARG+=($1)
    ;;

*)
    APP+=($1)
    esac
    shift
done


for i in $APP
do
    if [[ -d $i ]]
    then
        echo cd $i
        echo git pull --rebase
    else
        echo git clone https://aur.archlinux.org/$i.git
        echo cd $i
    fi
    echo makepkg -si --needed $ARG
    echo cd ../
done
