#!/bin/zsh

FILE=/etc/systemd/system/getty@tty1.service.d/override.conf

cat <<EOF | sudo su
mkdir -p $(dirname $FILE)
echo "[Service]
ExecStart=
ExecStart=-/usr/bin/agetty -n -o $USER --noclear %I \$TERM" >$FILE
EOF
