#!/bin/zsh

set -e
test $(whoami) != 'root'

cd
DIR=code/config
for F in $(ls $DIR -I "*.txt" -I LICENSE -I README.md)
do
    H=$(head -n 1 $DIR/$F)

    APP=$(echo $H | awk '{print $3}')

    if pacman -Q $APP &>/dev/null
    then
        T=$(echo $H | awk '{print $2}')

        if ! cmp --silent $T $DIR/$F
        then
            cp -v $T $DIR/$F
        fi
    fi
done
