#!/bin/zsh

set -e
test $(whoami) != 'root'

cd
DIR=code/config
for F in $(ls $DIR -I "*.txt" -I LICENSE -I README.md)
do
    H=$(head -n 1 $DIR/$F)

    APP=$(echo $H | awk '{print $3}')

    if pacman -Q $APP &>/dev/null
    then
        T=$(echo $H | awk '{print $2}')

        if [ $(echo $T | cut -c 1) = '/' ]
        then
            sudo mkdir -pv $(dirname $T)
            sudo cp -v $DIR/$F $T
        else
            mkdir -pv $(dirname $T)
            cp -v $DIR/$F $T
        fi
    fi
done

DIR=code/script/pkg
for i in $(ls $DIR)
do
    if pacman -Q $i &>/dev/null
    then
        echo "Running script for $i"
        ./$DIR/$i
    fi
done
