#!/bin/zsh

if [ `whoami` = 'root' ]
then
    echo "Don't run as root"
    exit
fi

DIR=$HOME/code/config
if ! [ -d $DIR ]
then
    git clone "https://github.com/albymath/config.git" $DIR
fi
cd $HOME

for from in $(ls $DIR -I "*.txt" -I LICENSE -I README.md)
do
    app=$(head -n 1 $DIR/$from | awk '{print $3}')
    if pacman -Q $app &>/dev/null
    then
        to=$(head -n 1 $DIR/$from | awk '{print $2}')
        if [ $(echo $to | cut -c 1) = '/' ]
        then
            sudo mkdir -pv $(dirname $to)
            sudo cp -v $DIR/$from $to
        else
            mkdir -pv $(dirname $to)
            cp -v $DIR/$from $to
        fi
    fi
done

DIR=$HOME/code/script/app-specific
for i in $(ls $DIR)
do
    if pacman -Q $i &>/dev/null
    then
        $DIR/$i
    fi
done
