#!/bin/zsh

DIR=$HOME/code/suckless
APP=(dwm st dmenu)

if ! [ -d $DIR ]
then
    mkdir -p $DIR
fi
cd $DIR

sudo pacman --noconfirm --needed -S base-devel terminus-font
for P in $APP
do
    if ! [ -d $P ]
    then
        git clone "https://github.com/albymath/${P}.git"
    fi
    sudo make -C $P clean install
done
