#!/bin/zsh

DIR=$HOME/code/config

if [ `whoami` = 'root' ]
then
    echo "Don't run as root"
    exit
fi

if ! [ -d $DIR ]
then
    git clone "https://github.com/albymath/config.git" $DIR
fi

cd $HOME
for from in $(ls $DIR -I "*.txt" -I LICENSE -I README.md)
do
    app=$(head -n 1 $DIR/$from | awk '{print $3}')
    if pacman -Qq $app &>/dev/null
    then
        to=$(head -n 1 $DIR/$from | awk '{print $2}')
        if ! cmp --silent $to $DIR/$from
        then
            cp -v $to $DIR/$from
        fi
    fi
done
