#!/bin/zsh

# Install packges
sudo -H pacman -S --noconfirm --needed \
    python python-pip python-lxml python-babel \
    uwsgi uwsgi-plugin-python \
    git base-devel libxml2 \
    shellcheck

# Create user
sudo -H useradd --shell /bin/bash --system \
  --home-dir "/usr/local/searx" \
  --comment 'Privacy-respecting metasearch engine' searx
sudo -H mkdir "/usr/local/searx"
sudo -H chown -R "searx:searx" "/usr/local/searx"

# Install searx & dependencies
cat <<EOF | sudo -H -u searx -i
git clone "https://github.com/searx/searx.git" "/usr/local/searx/searx-src"

python3 -m venv "/usr/local/searx/searx-pyenv"
echo ". /usr/local/searx/searx-pyenv/bin/activate" >>  "/usr/local/searx/.profile"

pip install -U pip
pip install -U setuptools
pip install -U wheel
pip install -U pyyaml

cd "/usr/local/searx/searx-src"
pip install -e .
EOF

# Configguration
sudo -H mkdir -p "/etc/searx"
sudo -H cp "/usr/local/searx/searx-src/utils/templates/etc/searx/use_default_settings.yml" \
             "/etc/searx/settings.yml"

sudo -H sed -i -e "s/ultrasecretkey/$(openssl rand -hex 16)/g" "/etc/searx/settings.yml"
sudo -H sed -i -e "s/{instance_name}/searx@$(uname -n)/g" "/etc/searx/settings.yml"
