#!/bin/zsh

DIR=$HOME/code/suckless
APP=(dwm st dmenu)

set -e

if ! [ -d $DIR ]
then
    mkdir -p $DIR
fi
cd $DIR

sudo pacman --noconfirm --needed -S \
    base-devel libxft terminus-font \
    xf86-video-intel xorg-server \
    xorg-xbacklight xorg-xinput \
    xorg-xinit xorg-xsetroot

for P in $APP
do
    if ! [ -d $P ]
    then
        git clone "https://github.com/albymath/${P}.git"
    fi
    sudo make -C $P clean install
done

cd
echo "exec dwm" >.xinitrc
echo "exec startx" >.zprofile
