#!/bin/sh
while read file
do
        case "$1" in
        "d")
                mv "$file" ~/.local/share/Trash/files ;;
        "y")
                xclip -selection clipboard "$file" -t image/png ;;
        "r")
                convert -rotate 90 "$file" "$file" ;;
        "R")
                convert -rotate -90 "$file" "$file" ;;
        "w")
                nitrogen --set-zoom-fill "$file"
                cp "$file" $HOME/pic/.wallpaper ;;
        "g")
                gimp "$file" & ;;
        esac
done
