#!/bin/zsh

FILE=/usr/share/applications/sxiv.desktop
MIME=(`grep MimeType $FILE | cut -c 10- | tr ';' ' '`)
xdg-mime default sxiv.desktop $MIME
echo $MIME

cd
mkdir -p ".config/sxiv/exec"
cp "code/script/sxiv-keyhandler" ".config/sxiv/exec/key-handler"
